###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts/6744d08cd35b6b6c09337852

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "TEST",
    "content": "TEST",
    "owner": "TEST"
}