###

POST http://localhost:3000/comments
Content-Type: application/json

{
    "postId": "673db4d795e9de7db703694f",
    "content": "This is a comment.",
    "author": "John Doe"
}

###

GET http://localhost:3000/comments/67462f7a84ea9a135866e1dd

