###

POST http://localhost:3000/comments
Content-Type: application/json

{
    "postId": "673db4d795e9de7db703694f",
    "content": "This is a comment.",
    "author": "John Doe"
}

###

GET http://localhost:3000/comments/67437137c383bfaaa3d06d63

###

PUT http://localhost:3000/comments/67437137c383bfaaa3d06d63
Content-Type: application/json

{
    "content": "Update Comment"
}

