###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts/6745d7a8d0524dbda22ba039

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "TEST",
    "content": "TEST",
    "owner": "Nadav"
}

###

GET http://localhost:3000/posts?owner=Nadav

###

PUT http://localhost:3000/posts/6745d7a8d0524dbda22ba039
Content-Type: application/json

{
    "title": "UPDATE1",
    "content": "UPDATE1",
    "owner": "TEST"
}
