###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts/6745d7a8d0524dbda22ba039

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "TEST",
    "content": "TEST",
    "sender": "LI"
}

###

GET http://localhost:3000/posts?sender=

###

PUT http://localhost:3000/posts/674649d4d0524dbda22ba057
Content-Type: application/json

{
    "title": "UPDATE6",
    "content": "UPDATE6"
}
